# Generated by Django 6.0 on 2026-01-17 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TheDateEntered', models.DateTimeField(auto_now_add=True)),
                ('TheVehicleMake', models.CharField(choices=[('Alfa Romeo', 'Alfa Romeo'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Mercedes Benz', 'Mercedes Benz'), ('Mini cooper', 'Mini cooper'), ('Mitsubishi', 'Mitsubishi'), ('Subaru', 'Subaru'), ('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], max_length=50)),
                ('TheDriverName', models.CharField(default='Null', max_length=50)),
                ('TheColor', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Green', 'Green'), ('Red', 'Red'), ('Blue', 'Blue'), ('Silver', 'Silver'), ('Grey', 'Grey')], max_length=50)),
                ('TheRegistrations', models.CharField(default=False, max_length=12, null=True)),
                ('ThePhoneNumber', models.IntegerField()),
                ('TheStatus', models.CharField(choices=[('Drive In', 'Drive In'), ('Washing in Progress', 'Washing in Progress'), ('Car wash Finished', 'Car wash Finished')], default='None', max_length=50, null=True)),
                ('TheUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
