# Generated by Django 6.0 on 2026-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0002_alter_vehiclemodel_theuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='ThePhoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
