# Generated by Django 6.0 on 2026-01-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0003_alter_vehiclemodel_thephonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='TheDriverName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='TheRegistrations',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
