# Generated by Django 6.0 on 2026-01-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwashapp', '0004_alter_vehiclemodel_thedrivername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='TheStatus',
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='TheColor',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Green', 'Green'), ('Red', 'Red'), ('Blue', 'Blue'), ('Silver', 'Silver'), ('Grey', 'Grey'), ('Yellow', 'Yellow')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='TheVehicleMake',
            field=models.CharField(choices=[('Alfa Romeo', 'Alfa Romeo'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Mercedes Benz', 'Mercedes Benz'), ('Mini cooper', 'Mini cooper'), ('Mitsubishi', 'Mitsubishi'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], max_length=50),
        ),
    ]
